- name: Create network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Deploy services
  include_tasks:
    file: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
  tags: "api"
