- name: Deploy / build server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: swarm_init
      tags: swarm_init

- name: Managers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join
