- name: "[{{ name }}] Secret configuration"
  include_tasks:
    file: "../secret.yml"
    apply:
      tags: "{{ name }}"
  tags: "{{ name }}"

- name: "[{{ name }}] Deploy service"
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}/{{ name }}:{{ version }}"
        state: present
        networks:
          - "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3002
            target_port: 3000
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
