- name: "[{{ name }}] Secret configuration"
  include_tasks:
    file: "../secret.yml"

- name: "[{{ name }}] Deploy service"
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        force_update: true
        networks:
          - "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            target_port: 3000
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
