galaxy_info:
  role_name: preconfig
  description: Configuration servers for Docker
  author: Syringe
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ubuntu
      version:
        - all
