- name: Swarm init
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Dir exist
  file:
    path: ./tokens
    mode: "0644"
    state: directory
  delegate_to: localhost

- name: Saving manager's token
  copy:
    dest: ./tokens/token-manager
    mode: "0644"
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
  delegate_to: localhost

- name: Saving worker's token
  copy:
    dest: ./tokens/token-worker
    mode: "0644"
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
  delegate_to: localhost
