- name: "[{{ name }}] Config configuration"
  block:
    - name: "[{{ name }}] Create config"
      include_tasks:
        file: "config-create.yml"

  rescue:
    - name: "[{{ name }}] Delete service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Create config"
      include_tasks:
        file: "config-create.yml"
