---
- name: Docker Install
  block:
    - name: Add universe
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Install additional package
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400

    - name: Add Docker key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"
        state: present

    - name: Set up stable repository
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Install Docker-ce
      apt:
        name: docker-ce
        update-cache: true

    - name: Docker check
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Install Docker-compose
  block:
    - name: Get last version
      uri:
        url: "https://api.github.com/repos/docker/compose/releases/latest"
        body_format: json
      register: version

    - name: Install
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ version.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
  become: true

- name: Install additional packages of python
  block:
    - name: Install pip packages
      pip:
        name: docker

- name: Complete installation
  block:
    # - name: Add Docker group
    #   group:
    #     name: docker
    #     state: present

    - name: Add user in the Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    # - name: reboot
    #   reboot:
  become: true
