galaxy_info:
  role_name: node_leave
  description: Disconnect node from swarm
  author: Syringe
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ubuntu
      version:
        - all
